name: Prod

# Runs tests on push in main and update prod server
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      # Getting the code
      - uses: actions/checkout@v4
      # Install python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install requirements
        # Installing project and testing dependencies
        run: | 
          pip install -r fastapi/requirements.txt
          pip install coverage httpx
        # Run tests
      - name: Run tests
        run: coverage run fastapi/tests.py
        # Show coverage report
      - name: Tests report
        run: coverage report

  deploy-ssh:
    # Runs if docker image is pushed
    needs: 'test'
    runs-on: [ubuntu-latest]
    environment: must-review
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_PROD_HOST}}
          user: ${{secrets.SSH_PROD_USER}}
          private_key: ${{secrets.SSH_PROD_PRIVATE_KEY}}
          command: |
            cd ${{ secrets.PROD_PROJECT_FOLDER }};
            git pull;
            docker compose build;
            docker compose down;
            docker compose up -d;